import type { Metadata } from "next";
import "./globals.css";
import db from "@/lib/supabase/db";
import { ThemeProvider } from "@/lib/providers/next-theme-provider";
import { DM_Sans } from "next/font/google";
const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OpusVita",
  description: "Generated by Divyansh Dubey",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(db);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class"
        defaultTheme="dark"
        enableSystem>
        {children}
        </ThemeProvider>
        </body>
    </html>
  );
}
